image: Visual Studio 2017
configuration:
  - Release
  - Debug
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: OP2Script.sln
after_build:
  - set PackageBaseName="%APPVEYOR_PROJECT_NAME%-Build%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%"
  - 7z a "%PackageBaseName%.zip" "%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*.dll"
  - 7z a "%PackageBaseName%-DebugSymbolPdb.zip" "%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*.pdb"
artifacts:
  - path: "*.zip"
    name: BuildArtifacts
